spring:
  application:
    name:SpringBootWithDocker

    # Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

  datasource:
      url: jdbc:mysql://mysql-container:3306/mydatabase
      username: root
      password: "password"
      # Hibernate Properties
  jpa:
      show-sql: false
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
